# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Conference Series"
  weight = 10
[[main]]
  name = "Series Overview"
  url = "series/#"
  parent = "Conference Series"
  weight = 10
[[main]]
  name = "Committee"
  url = "series/#committee"
  parent = "Conference Series"
  weight = 20
[[main]]
  name = "Conferences"
  url = "series/#conferences"
  parent = "Conference Series"
  weight = 30
[[main]]
  name = "Proceedings"
  url = "series/#proceedings"
  parent = "Conference Series"
  weight = 40
[[main]]
  name = "Organization"
  url = "series/#orga"
  parent = "Conference Series"
  weight = 50



[[main]]
  name = "CLARIN K-Centre for CMC"
  weight = 20
[[main]]
  name = "CKCMC Overview"
  url = "ckcmc/#"
  parent = "CLARIN K-Centre for CMC"
  weight = 10
[[main]]
  name = "Partners"
  url = "ckcmc/#partners"
  parent = "CLARIN K-Centre for CMC"
  weight = 20
[[main]]
  name = "Documentation"
  url = "ckcmc/docs/"
  parent = "CLARIN K-Centre for CMC"
  weight = 30


[[main]]
  name = "CMC-TEI"
  url = "ckcmc/docs/tei/"
  weight = 30

[[main]]
  name = "Publications"
  url = "publication/"
  weight = 40

[[main]]
  name = "News"
  url = "post/"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
