# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image:
  name: klakegg/hugo:ext-debian
  entrypoint : ['']

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  before_script:
  - apt update && apt install -y git
  - git submodule update --init --recursive
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
