---
image:
  name: klakegg/hugo:ext-ubuntu
  entrypoint: ['']

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo
  except:
    - master
    - dev
    - tags

# FIXME: part I
#
# Needs to be renamed 'pages' for gitlab to generate pages.
pages-master:
  before_script:
    - apt update && apt install -y git
  script:
    - go version
    - hugo version
    - hugo --baseURL https://ckcmc.gitlab.io/
  artifacts:
    paths:
      - public
  only:
    - disabled

# Onle *pages* makes gitlab generate pages!
pages:
  script:
    - hugo version
    - make generate
  artifacts:
    paths:
      - public
  only:
    - master
